plugins { id 'com.android.application' }

android {
    enableKotlin = false
    namespace 'io.github.adityamagar.autoskip'
    compileSdk { version = release(37) }

    defaultConfig {
        applicationId 'io.github.adityamagar.autoskip'
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName '0.1.0'
        testInstrumentationRunner 'io.github.adityamagar.autoskip.SmokeInstrumentation'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
